spring.application.name=Abgabe_Gruppe2

# H2 Datenbank im File-Modus (wird als Datei gespeichert)
spring.datasource.url=jdbc:h2:file:./data/filmdatenbank
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console (erreichbar unter http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Thymeleaf Warning unterdrücken (optional)
spring.thymeleaf.check-template-location=false